# ==============================
# DATABASE
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/ocioteca
spring.datasource.username=your_username
spring.datasource.password=your_password

# ==============================
# API KEYS
# ==============================
google.books.key=YOUR_GOOGLE_BOOKS_KEY
tmdb.key=YOUR_TMDB_KEY