spring.application.name=Plataforma

# application.properties

# Configuraci\u00c3\u00b3n de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/plataforma?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci\u00c3\u00b3n de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
